version: '3'
services:
  api:
    build:
      context: .
    container_name: microservice_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge